name: cd_fork
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v2.13
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          changelog-path: docs/changelog.md
          package-name: streetmerchant
      - name: login into github package registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: build latest docker image
        run: |
          docker build \
          -t "ghcr.io/${GITHUB_REPOSITORY}:nightly" \
          -t "ghcr.io/${GITHUB_REPOSITORY}:latest" .
        env:
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
      - name: publish latest image
        run: docker push "ghcr.io/${GITHUB_REPOSITORY}"
